$axure.loadCurrentPage({
  "url":"流程图.html",
  "generationDate":new Date(1660115816729.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aeb1a9edbff1443fbb495db24ccb4ef7",
    "type":"Axure:Page",
    "name":"流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"385979ffd36640d8b2f4a290b3b69fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1120},
            "size":{
              "width":1068,
              "height":980}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92c0142000d04bb7afda13ffe81bac26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1120},
                "size":{
                  "width":1068,
                  "height":980}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"55584b2c0dc242d4a060ad8fb9569813",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":2140},
            "size":{
              "width":1068,
              "height":1359}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c15737be6a734387927b9275b7c8c3f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":2140},
                "size":{
                  "width":1068,
                  "height":1359}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u2.png"}},
{
          "id":"3929f8f62cad4777b86e4febf76028bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":40},
            "size":{
              "width":1068,
              "height":1048}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dddb81cbe1854e38b954cfffaa883be2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":40},
                "size":{
                  "width":1068,
                  "height":1048}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "385979ffd36640d8b2f4a290b3b69fae":{
      "scriptId":"u0"},
    "92c0142000d04bb7afda13ffe81bac26":{
      "scriptId":"u1"},
    "55584b2c0dc242d4a060ad8fb9569813":{
      "scriptId":"u2"},
    "c15737be6a734387927b9275b7c8c3f2":{
      "scriptId":"u3"},
    "3929f8f62cad4777b86e4febf76028bd":{
      "scriptId":"u4"},
    "dddb81cbe1854e38b954cfffaa883be2":{
      "scriptId":"u5"}}});