$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1659951212397.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a9bae162f6d445c88c2a5c93b7832156",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 p1",
                "objectsToFades":[{
                    "objectPath":["bf09bea704b64b4491d147bad66e347c"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"e8a0c55c6ae44262bd52b1485be22916",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":42},
            "size":{
              "width":332,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2a71fca58784a87bd89320aca933960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":42},
                "size":{
                  "width":332,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10b57748af434682bc9d613f0745695b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":110},
            "size":{
              "width":250,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d7a0a443b374340ab16f2b26eb4c106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":110},
                "size":{
                  "width":250,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"91ac48735c8944c7a8db85d68537b3f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":130},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109ba5bfa9544747b8a2df3c675f474f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":130},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"692569290e4248c794832caf3ac565e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":356,
              "y":130},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1500c01bd3814915bc603ebceb11fcf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":356,
                  "y":130},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 p1",
                      "objectsToFades":[{
                          "objectPath":["bf09bea704b64b4491d147bad66e347c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"c37785fb2259409ea8547d65922e82da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":240},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06e3a0fbafdc4bac8d5e1b33671a10e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":240},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"bf09bea704b64b4491d147bad66e347c",
          "label":"p1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":230},
            "size":{
              "width":470,
              "height":200}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":270,
          "fixedVertical":"top",
          "fixedMarginVertical":230,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"eba1255302f34e2ca90dbe8bc0316ca8",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f927fd831d8645ba953ef23bfdc71e9d",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":20},
                    "size":{
                      "width":300,
                      "height":152}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4111cf9d19b408592ba913c39c24a89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":70,
                          "y":20},
                        "size":{
                          "width":300,
                          "height":152}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u11.png"}},
{
                  "id":"158a7155350d469ab0062e4cc472971c",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"cf8830bd97aa4a538d3a6569e254508e",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"69b4a504d9584d6498fe66f0a3b5677f",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":80},
                    "size":{
                      "width":28,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b8fc94682c44c80926c1b914ea963d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":80},
                        "size":{
                          "width":28,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"41a5a1d0c18045e2bff2adaf5ed89384",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":172,
                      "y":72},
                    "size":{
                      "width":142,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"7f748caa1562452bad79e979732cf1c4",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":40},
                    "size":{
                      "width":54,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a7043ef1851425389aaf602ebf3e3ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":40},
                        "size":{
                          "width":54,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c56a761fae3a4f019f2cfe196c942514",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"ac0df485f7a54e26a638dc2d7a606ae3",
                  "label":"",
                  "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":340,
                      "y":18.0000019073486},
                    "size":{
                      "width":22,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0c4266a76654847b4faf9666ac788f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf09bea704b64b4491d147bad66e347c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":340,
                          "y":18.0000019073486},
                        "size":{
                          "width":22,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 p1",
                              "objectsToFades":[{
                                  "objectPath":["bf09bea704b64b4491d147bad66e347c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"7413d88bb2ac468798f316c67d541595",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]}]}},
  "masters":{
},
  "objectPaths":{
    "e8a0c55c6ae44262bd52b1485be22916":{
      "scriptId":"u0"},
    "d2a71fca58784a87bd89320aca933960":{
      "scriptId":"u1"},
    "10b57748af434682bc9d613f0745695b":{
      "scriptId":"u2"},
    "9d7a0a443b374340ab16f2b26eb4c106":{
      "scriptId":"u3"},
    "91ac48735c8944c7a8db85d68537b3f9":{
      "scriptId":"u4"},
    "109ba5bfa9544747b8a2df3c675f474f":{
      "scriptId":"u5"},
    "692569290e4248c794832caf3ac565e3":{
      "scriptId":"u6"},
    "1500c01bd3814915bc603ebceb11fcf9":{
      "scriptId":"u7"},
    "c37785fb2259409ea8547d65922e82da":{
      "scriptId":"u8"},
    "06e3a0fbafdc4bac8d5e1b33671a10e9":{
      "scriptId":"u9"},
    "bf09bea704b64b4491d147bad66e347c":{
      "scriptId":"u10"},
    "f927fd831d8645ba953ef23bfdc71e9d":{
      "scriptId":"u11"},
    "a4111cf9d19b408592ba913c39c24a89":{
      "scriptId":"u12"},
    "158a7155350d469ab0062e4cc472971c":{
      "scriptId":"u13"},
    "cf8830bd97aa4a538d3a6569e254508e":{
      "scriptId":"u14"},
    "69b4a504d9584d6498fe66f0a3b5677f":{
      "scriptId":"u15"},
    "2b8fc94682c44c80926c1b914ea963d8":{
      "scriptId":"u16"},
    "41a5a1d0c18045e2bff2adaf5ed89384":{
      "scriptId":"u17"},
    "7f748caa1562452bad79e979732cf1c4":{
      "scriptId":"u18"},
    "6a7043ef1851425389aaf602ebf3e3ed":{
      "scriptId":"u19"},
    "c56a761fae3a4f019f2cfe196c942514":{
      "scriptId":"u20"},
    "ac0df485f7a54e26a638dc2d7a606ae3":{
      "scriptId":"u21"},
    "a0c4266a76654847b4faf9666ac788f3":{
      "scriptId":"u22"}}});