$axure.loadCurrentPage({
  "url":"待处理事项.html",
  "generationDate":new Date(1659951212543.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"554e86b135494bf3954b550a26df4fd3",
    "type":"Axure:Page",
    "name":"待处理事项",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e1eff3f34e3f432797ee6e324385b36c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":90},
            "size":{
              "width":800,
              "height":132}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80591219395041ad83a047cc82d0c5ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97e81227a8a24a75a6fe3f58db7611af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"b2a2f45f7d224f2fa137a633e283726d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7da76006c86f444f8263f53daedd8c57",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"5b6498f21b444ba2ae34d68000ce6389",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":72},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9dbb5a1334749d69066e1b94d4bec26",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":72},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"8a2860fdb28542bab951fbc71376974f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":120,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8273c5e1ea3145988e927bf506cdc578",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u3.png"}},
{
              "id":"b41ae554dfdd4964b74f9fe0aa7e34d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":120,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c550c01b2bea4c6a9f3be620c7c6333f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":120,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u3.png"}},
{
              "id":"8659c19162cb444893ac3698aac6d0ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":72},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5f833a5960e43d180f4467ec4c5eb90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":72},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u35.png"}},
{
              "id":"07242d22cf2a40bfaad5800a36160736",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":220,
                  "y":0},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"368a000f72d245e7b8981ab62172b2af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":220,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u5.png"}},
{
              "id":"19d90531204e460fa2644400d1449b30",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":220,
                  "y":36},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c5a9c649ec304c3a9633463df91ab778",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":220,
                      "y":36},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u5.png"}},
{
              "id":"d0ae498872054dd9b8091741c3b4e7a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":220,
                  "y":72},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"661dd078fccc40469d1002242789935f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":220,
                      "y":72},
                    "size":{
                      "width":80,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u37.png"}},
{
              "id":"1523b02198fd4f5ba8e7ee289a3ba779",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9081c6e933524de284fa216bc862d9f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"d9be8ec8071a46b19e4ea0e250132096",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":36},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e4baa2c6f9c401abc261becf7c2d62a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"66d230fecce64ce4ba5c9bde38adb9c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":72},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"364f38a098bc4bc9a44f366f045d2f66",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":72},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"ccb19f7994fb4427805d28f7aa5e17d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab262d11a6984fcb8e182d73e64a147a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"8afcbec818154551a3cd2016303d3cc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":36},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ec258f96749452db209aa0f4dc7e345",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"f3fc9e7e90a2405a8066bb35da9cae5d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":72},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"417d428e767d4417bac2a3ef4ab5c745",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":72},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"ed4dbb3c77a14f9290ae5fbda3dd8dc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a9206d6431941cfa330caf0186246f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"7e911fa69e894ae59e8672377302e053",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c670aeb8088d4f32acea810b76e657b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"a5b11b1b483148b19261a2fcf612fe08",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":72},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a150fc900ba541cfa26d17e8f36899e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":72},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"e85224e2c98e425380063cafa2009f25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7af1c0cf2dd44ee4ac45d58ce88ecbc7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"7df8fa8d92804256858ab1c7d5504dd9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":36},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c234b1f6390c4e50aec8f72805135d84",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"96b957e336614c458c49377b061a0e2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":72},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87c2a986c8e94a0db927d61b1574d2e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":72},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"be7f3eadb9f041d5ac0e4b23d6d6bc97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f39c24e6edba4f29b66e806470b352a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u34.png"}},
{
              "id":"5137a35edf2f4f2b90f9e80e4ea15edb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":102},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e252142490fe4dce923e65859e9a45f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":102},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u51.png"}},
{
              "id":"8a8b87fb97fb43caa7d25a20c7eda220",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":220,
                  "y":102},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fb99bc60e624cf49cca875b8c0f7c9f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":220,
                      "y":102},
                    "size":{
                      "width":80,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u53.png"}},
{
              "id":"d93e0cd59e41407daf538bd5dcfcb7f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":102},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eeb2539bc2874b16aa5b3e5abf3687d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":102},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u34.png"}},
{
              "id":"2fb519cfc0394d94aa3bdb7b0104942f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":102},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc4ae29489114b9285bd0046fb1e7e9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":102},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u34.png"}},
{
              "id":"c402b9295b2f48108c2be4d73797edf3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":102},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0242352f84ab4360a5a6182c5ca5d9b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":102},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u34.png"}},
{
              "id":"27a4ba01a11243b5b01d42b462f8a8ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":102},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9d38fe3a3b54416b9a216974c67df7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":102},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u34.png"}},
{
              "id":"358a863f54af4619bee55f1d7f070516",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88afff6847ce45e08177b00105c2cf4e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u14.png"}},
{
              "id":"fbcd40ba580d4b22ba9a94ebe225211b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":36},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21724faa398c4e31b5dff663b94932ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":700,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u14.png"}},
{
              "id":"d02914ee53a34d06a4637633b99db931",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":72},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6ab248ee8b44cc9977d6deec9ac3d68",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":72},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u8.png"}},
{
              "id":"684bd9df3346445590c7b078bce1d444",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":102},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3afda5f4813c4f42b8e4e7225bee74cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":102},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u38.png"}}]},
{
          "id":"7bc6e911424f4a368a97830f958c0c16",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":290},
            "size":{
              "width":70,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2185dbec692144b3adb9ad4ffd39750a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ffe32ca91d3434b98ded0a7e9279cf4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u66.png"}},
{
              "id":"e669bbeb1f88462eaa90c728187a7168",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3137caa73fb4f3d8686b2cf7714ec68",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u66.png"}},
{
              "id":"3e0d3882b2c2429e97608ba646e3c12e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f3c95053fba4e309bf83658248cee8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待处理事项/u70.png"}}]},
{
          "id":"92fb61d4befd492fb52f8daf0a1e9c7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":140,
              "y":270},
            "size":{
              "width":680,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4508fad5ae1542d8a130c444d22ba0fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":140,
                  "y":270},
                "size":{
                  "width":680,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/待处理事项/u72.png"}},
{
          "id":"655caa419bea40f1a10550dbd76f9439",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":525},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"baa899f7f6ed4fd4bfc97f7855a1a19d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":525},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1b09a296bcdc49c1a5f86ddbe1752645",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":469.999969482422,
              "y":525},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f26409c1a66e4f888cc41502213bc8f0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":35},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f9a6eeb68dc7444e8bee29f12b09d538",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":32},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c94938ce3c7648ae9106384c5e0978a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":43},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df4e5506335d492ebf6bd79f9ea9e54b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":43},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72b03925c0bd4278811e5a6e007ec0eb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":357.5,
              "y":35},
            "size":{
              "width":142,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"599a98bbdb26412982d4ec49c79e25f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":35},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f5775c0cbbe408186ff1f4b2a14fffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":35},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7a945ee60d74d2482b1f9cac2261250",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":525},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9822a37bcccd43a5b1b50e40dac34e25",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":525},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9dcbeae471fc46598d2253bb53491f54",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":37},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"66836db73ebf4eeba06f6776b0a48184",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":37},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0748b83aa2dd4201883491894cf643aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":37},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e1eff3f34e3f432797ee6e324385b36c":{
      "scriptId":"u0"},
    "80591219395041ad83a047cc82d0c5ce":{
      "scriptId":"u1"},
    "97e81227a8a24a75a6fe3f58db7611af":{
      "scriptId":"u2"},
    "8a2860fdb28542bab951fbc71376974f":{
      "scriptId":"u3"},
    "8273c5e1ea3145988e927bf506cdc578":{
      "scriptId":"u4"},
    "07242d22cf2a40bfaad5800a36160736":{
      "scriptId":"u5"},
    "368a000f72d245e7b8981ab62172b2af":{
      "scriptId":"u6"},
    "ed4dbb3c77a14f9290ae5fbda3dd8dc8":{
      "scriptId":"u7"},
    "3a9206d6431941cfa330caf0186246f9":{
      "scriptId":"u8"},
    "1523b02198fd4f5ba8e7ee289a3ba779":{
      "scriptId":"u9"},
    "9081c6e933524de284fa216bc862d9f3":{
      "scriptId":"u10"},
    "ccb19f7994fb4427805d28f7aa5e17d2":{
      "scriptId":"u11"},
    "ab262d11a6984fcb8e182d73e64a147a":{
      "scriptId":"u12"},
    "e85224e2c98e425380063cafa2009f25":{
      "scriptId":"u13"},
    "7af1c0cf2dd44ee4ac45d58ce88ecbc7":{
      "scriptId":"u14"},
    "358a863f54af4619bee55f1d7f070516":{
      "scriptId":"u15"},
    "88afff6847ce45e08177b00105c2cf4e":{
      "scriptId":"u16"},
    "b2a2f45f7d224f2fa137a633e283726d":{
      "scriptId":"u17"},
    "7da76006c86f444f8263f53daedd8c57":{
      "scriptId":"u18"},
    "b41ae554dfdd4964b74f9fe0aa7e34d1":{
      "scriptId":"u19"},
    "c550c01b2bea4c6a9f3be620c7c6333f":{
      "scriptId":"u20"},
    "19d90531204e460fa2644400d1449b30":{
      "scriptId":"u21"},
    "c5a9c649ec304c3a9633463df91ab778":{
      "scriptId":"u22"},
    "7e911fa69e894ae59e8672377302e053":{
      "scriptId":"u23"},
    "c670aeb8088d4f32acea810b76e657b1":{
      "scriptId":"u24"},
    "d9be8ec8071a46b19e4ea0e250132096":{
      "scriptId":"u25"},
    "4e4baa2c6f9c401abc261becf7c2d62a":{
      "scriptId":"u26"},
    "8afcbec818154551a3cd2016303d3cc7":{
      "scriptId":"u27"},
    "9ec258f96749452db209aa0f4dc7e345":{
      "scriptId":"u28"},
    "7df8fa8d92804256858ab1c7d5504dd9":{
      "scriptId":"u29"},
    "c234b1f6390c4e50aec8f72805135d84":{
      "scriptId":"u30"},
    "fbcd40ba580d4b22ba9a94ebe225211b":{
      "scriptId":"u31"},
    "21724faa398c4e31b5dff663b94932ec":{
      "scriptId":"u32"},
    "5b6498f21b444ba2ae34d68000ce6389":{
      "scriptId":"u33"},
    "f9dbb5a1334749d69066e1b94d4bec26":{
      "scriptId":"u34"},
    "8659c19162cb444893ac3698aac6d0ff":{
      "scriptId":"u35"},
    "b5f833a5960e43d180f4467ec4c5eb90":{
      "scriptId":"u36"},
    "d0ae498872054dd9b8091741c3b4e7a0":{
      "scriptId":"u37"},
    "661dd078fccc40469d1002242789935f":{
      "scriptId":"u38"},
    "a5b11b1b483148b19261a2fcf612fe08":{
      "scriptId":"u39"},
    "a150fc900ba541cfa26d17e8f36899e0":{
      "scriptId":"u40"},
    "66d230fecce64ce4ba5c9bde38adb9c1":{
      "scriptId":"u41"},
    "364f38a098bc4bc9a44f366f045d2f66":{
      "scriptId":"u42"},
    "f3fc9e7e90a2405a8066bb35da9cae5d":{
      "scriptId":"u43"},
    "417d428e767d4417bac2a3ef4ab5c745":{
      "scriptId":"u44"},
    "96b957e336614c458c49377b061a0e2e":{
      "scriptId":"u45"},
    "87c2a986c8e94a0db927d61b1574d2e7":{
      "scriptId":"u46"},
    "d02914ee53a34d06a4637633b99db931":{
      "scriptId":"u47"},
    "b6ab248ee8b44cc9977d6deec9ac3d68":{
      "scriptId":"u48"},
    "be7f3eadb9f041d5ac0e4b23d6d6bc97":{
      "scriptId":"u49"},
    "f39c24e6edba4f29b66e806470b352a6":{
      "scriptId":"u50"},
    "5137a35edf2f4f2b90f9e80e4ea15edb":{
      "scriptId":"u51"},
    "e252142490fe4dce923e65859e9a45f4":{
      "scriptId":"u52"},
    "8a8b87fb97fb43caa7d25a20c7eda220":{
      "scriptId":"u53"},
    "4fb99bc60e624cf49cca875b8c0f7c9f":{
      "scriptId":"u54"},
    "d93e0cd59e41407daf538bd5dcfcb7f1":{
      "scriptId":"u55"},
    "eeb2539bc2874b16aa5b3e5abf3687d7":{
      "scriptId":"u56"},
    "2fb519cfc0394d94aa3bdb7b0104942f":{
      "scriptId":"u57"},
    "bc4ae29489114b9285bd0046fb1e7e9e":{
      "scriptId":"u58"},
    "c402b9295b2f48108c2be4d73797edf3":{
      "scriptId":"u59"},
    "0242352f84ab4360a5a6182c5ca5d9b4":{
      "scriptId":"u60"},
    "27a4ba01a11243b5b01d42b462f8a8ec":{
      "scriptId":"u61"},
    "e9d38fe3a3b54416b9a216974c67df7c":{
      "scriptId":"u62"},
    "684bd9df3346445590c7b078bce1d444":{
      "scriptId":"u63"},
    "3afda5f4813c4f42b8e4e7225bee74cd":{
      "scriptId":"u64"},
    "7bc6e911424f4a368a97830f958c0c16":{
      "scriptId":"u65"},
    "2185dbec692144b3adb9ad4ffd39750a":{
      "scriptId":"u66"},
    "2ffe32ca91d3434b98ded0a7e9279cf4":{
      "scriptId":"u67"},
    "e669bbeb1f88462eaa90c728187a7168":{
      "scriptId":"u68"},
    "a3137caa73fb4f3d8686b2cf7714ec68":{
      "scriptId":"u69"},
    "3e0d3882b2c2429e97608ba646e3c12e":{
      "scriptId":"u70"},
    "5f3c95053fba4e309bf83658248cee8f":{
      "scriptId":"u71"},
    "92fb61d4befd492fb52f8daf0a1e9c7c":{
      "scriptId":"u72"},
    "4508fad5ae1542d8a130c444d22ba0fc":{
      "scriptId":"u73"},
    "655caa419bea40f1a10550dbd76f9439":{
      "scriptId":"u74"},
    "baa899f7f6ed4fd4bfc97f7855a1a19d":{
      "scriptId":"u75"},
    "1b09a296bcdc49c1a5f86ddbe1752645":{
      "scriptId":"u76"},
    "f26409c1a66e4f888cc41502213bc8f0":{
      "scriptId":"u77"},
    "f9a6eeb68dc7444e8bee29f12b09d538":{
      "scriptId":"u78"},
    "c94938ce3c7648ae9106384c5e0978a9":{
      "scriptId":"u79"},
    "df4e5506335d492ebf6bd79f9ea9e54b":{
      "scriptId":"u80"},
    "72b03925c0bd4278811e5a6e007ec0eb":{
      "scriptId":"u81"},
    "599a98bbdb26412982d4ec49c79e25f4":{
      "scriptId":"u82"},
    "4f5775c0cbbe408186ff1f4b2a14fffd":{
      "scriptId":"u83"},
    "f7a945ee60d74d2482b1f9cac2261250":{
      "scriptId":"u84"},
    "9822a37bcccd43a5b1b50e40dac34e25":{
      "scriptId":"u85"},
    "9dcbeae471fc46598d2253bb53491f54":{
      "scriptId":"u86"},
    "66836db73ebf4eeba06f6776b0a48184":{
      "scriptId":"u87"},
    "0748b83aa2dd4201883491894cf643aa":{
      "scriptId":"u88"}}});