$axure.loadCurrentPage({
  "url":"注册、登录.html",
  "generationDate":new Date(1660199389538.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bc9c0331f294453884fccdc55ab8e06f",
    "type":"Axure:Page",
    "name":"注册、登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"560780f4bbe643699c258ded15ca90c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":30},
            "size":{
              "width":300,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306efb05eab448f6852a40b22f494e29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":30},
                "size":{
                  "width":300,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录/u0.png"}},
{
          "id":"8cb2ae04d5f2454e920e1075d84b4629",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":90,
              "y":162},
            "size":{
              "width":193,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2cda5bcaa03423591470060c313403a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":90,
                  "y":162},
                "size":{
                  "width":193,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"feae179bf47c49b5b67d3a928b82aeff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":90,
              "y":106},
            "size":{
              "width":193,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b01ad5fced94cfe9072a2a65b34efc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":90,
                  "y":106},
                "size":{
                  "width":193,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c23901a911e4f2fae4d42a98426612b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":90,
              "y":50},
            "size":{
              "width":193,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"115be9fdc8e148b784156637432c3c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":50},
                "size":{
                  "width":193,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72d28f1da9e84fc7bd5de5f531da3098",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":240},
            "size":{
              "width":340,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c525dba787694edebfd2a8aca4ad40a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":240},
                "size":{
                  "width":340,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录/u8.png"}},
{
          "id":"ea3a98fea02b4d9f88eb3b406ea550c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":252},
            "size":{
              "width":332,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"720d83d2e71e4fe6a0b634fdb51e98ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":252},
                "size":{
                  "width":332,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eb2541edeac4c7782ace6cca321648d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":310},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e010bb22b72f4464842c4ba7946e6a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":310},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a6b8c1846f4b01b0f4d1e270343dba",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":306},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"089eb429cf6d4e9d95e7e2585563f6e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":340},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a111a70565214a748c24ca3863223995",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":340},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5314c218117d40aa9e9a0efc62ccd73f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":336},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"05a010b387674d758026ff35bde76f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":370},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6411507f899a48d78737d77d22719393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":370},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7776f07dcc1b44498637fb09742d4dec",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":366},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4a4e325c0f9f49adbb8698bf6a94bc12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":405},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e47d1cc657f74f1d8def6b7257951a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":405},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f60d732cc7ae4eb1a22740d9f8cae969",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":401},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f3da2aeda11644ecb8ecb39e7ba2fe95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":440},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1fce4b7c9b54745ba755a24033e5f08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":440},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef0de0518ed248b5b52f110f8ffada10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":436},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"364551fb013242deab069e6067c67cc3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":436},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b494225763b14af5a8d434beb095c6dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":475},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4a7a96dfa104f30aecfbc6ead862504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":475},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f92c51627db0451ba36334f71545e4ea",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":471},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9e950f3590ad4e008688f423ed8baea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":510},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2621ff749ef0432ea9f10950abaea115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":510},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"175e33710f0c47e3ba6a8d5e6e7cd2db",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":506},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d9e4ed1c89ec4331b605a4e79e81dd2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":540},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35154b72d65044b29f65cc6b5dce4413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":540},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2e38558dba54e4a91a44af0557a4c2c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":536},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7db057a2e581439d89171eb6be9c8053",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":595},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e2b4fb7b5d9247c7a0136a07fe3e4e62",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":595},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1ce8b679787842c799b52407adef7e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":232},
            "size":{
              "width":330,
              "height":446}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166e288cc0e04bee81866ceab489c08e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":232},
                "size":{
                  "width":330,
                  "height":446}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录/u39.png"}},
{
          "id":"14fba26200034bc8ac1dc3ed3a5d2cd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":440.000030517578,
              "y":240},
            "size":{
              "width":332,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b97bd721a57140ff9e4be7b7ba31336f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440.000030517578,
                  "y":240},
                "size":{
                  "width":332,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02ea46b71de048348316aa84210d0926",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":467.000030517578,
              "y":338},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"051ef89d53334afcb191e5d183973bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467.000030517578,
                  "y":338},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"115d4c8b82ca445aa4ade5262ec98c51",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":334},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3106734740df434bbf19428870c70a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":467.000030517578,
              "y":368},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cafb3989a0e4a208cc213bc97027075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467.000030517578,
                  "y":368},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b3efd7ff5d1471492ad8be7acea8f86",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":364},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1591c4cf178643ca84f2aad7d88cb6c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":467.000030517578,
              "y":433},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e309d7fd082446b869333e474ad9363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467.000030517578,
                  "y":433},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07600ee5e9724b488d99b44aab443898",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":429},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6040f6a1a8724b8db0bb925601bf4371",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":467.000030517578,
              "y":468},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d37c3f2ec11844e3a0542b473eebcd85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467.000030517578,
                  "y":468},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac2e0122652e40a08c66c99cf385bcff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":464},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b65d9a2f21b443d7b3cc086c7c8700f8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":464},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"74c712c9739a42b4af17fbf7670c3114",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":508},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"16314046a59848d2aefc262be5133323",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":394},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"15334f0d27ca49e79d3dcc5a3f9463c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":60},
            "size":{
              "width":750,
              "height":700}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c8734452b49447794e8ad9bc8edd54d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":60},
                "size":{
                  "width":750,
                  "height":700}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录/u58.png"}},
{
          "id":"eead397b0db44a99be5091deff456d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":809.5,
              "y":82},
            "size":{
              "width":321,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"419da717eb284bc5a8284e3790b427e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809.5,
                  "y":82},
                "size":{
                  "width":321,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6ffd5499a944853b1d306b3505c5e1f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":150},
            "size":{
              "width":710,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"779faf8c0fce4f9285f2dec1dc9183bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0a8f02021f2436da9fa15a9ab88491f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"27014dad604142a3808eaaac8cf7b5a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c47cb0d54204c5aa1499e290cfd9233",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"f6b8fff8bc64477986f8a6e8bea5409a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc6e729ea2154b71a36e9a7b40c37832",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"8092171ea70e43798826375c2c4fba82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":89,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8417a7bacd4646e79be6cf99c3cd247c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":89,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"e6d9541e949249fe892b5e935dd26da1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":89,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a741888db4084806882c5709a1164f02",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":89,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"146f1f9ec5ad442c930a5173e3213128",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":89,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"054299ef9b994955be800d7d0689ef0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":89,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"9789031b688740e0b75964defd60128b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd2bf21afb694ad1b354b9e066e42318",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"4cde0d11d7924c9ea1ce72af54a1ebc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d681f4eff36409d916d35220a0a6850",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"ad83a331e4144019b166816865bda767",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b6106c39bf34b09a1b324ab34a98864",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"e19ef3b22cdc401c85fdf31ba63a90d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ee5e378be544271a7b02e6b80924453",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"80d7c79ecef44090a51c592553dddd1f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c2710bf7ea64ef3aaa9eab174e611fb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"7ba8c24992664320b278e6b30e9d0faa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2468cc109a94456db7e06ab144ff5ba3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"343b2c128f414c059b263d4bf02fcba6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":445,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f359c193e9f47b581bc7f6b24a9bd55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":445,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"4b268b593a374f38bedd8c89eb4ae414",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":445,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40111fbf302242b1ba16374ed6f2cf1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":445,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"52336e439d244d6196fc95b0ff3d4d3d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":445,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e57ce29f042e48869357ce373ecad700",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":445,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"407137bf6e024e7f97ddd63a2e4ce20b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb6a93f60c994b249a2cab8db7896e43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"2f9f4f51cddb4eb5973c5013c55c59d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b2c59550ab04509b30d19612ec2cd71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"7972db29342e4abe95a94f1029a6d780",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ebfdd089648147adb4ec9cb2d27ce478",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"fad83039f2f1465ab9a1f55da56b08d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0395f88002f249da965cfbb1cb78ff76",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"13e349bcbea849f6b35c5e79d7bdf6c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":30},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b97fddffedec4112a5ef1e7e631380f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u63.png"}},
{
              "id":"0e1f7784255c45dcba719c56ba68039d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":60},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6eb36345d8445b090a390001067aae3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":60},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u95.png"}},
{
              "id":"96f9a1c2981c4cd8961932482e800a46",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":623,
                  "y":0},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82a35f4ade9f4c7e8e0bcfc4f2e08ea0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":623,
                      "y":0},
                    "size":{
                      "width":87,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u77.png"}},
{
              "id":"2f8e844203394dcca37acebd2f71b226",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":623,
                  "y":30},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7281075920de43979446ca9280925791",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":623,
                      "y":30},
                    "size":{
                      "width":87,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u77.png"}},
{
              "id":"b4399fb9e74146179e5e0602b2d1ec23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":623,
                  "y":60},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03015ef37cee423ba089924f9a6bf8ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":623,
                      "y":60},
                    "size":{
                      "width":87,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册、登录/u109.png"}}]},
{
          "id":"6bb8487420404448a389409308277a8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":280},
            "size":{
              "width":330,
              "height":393}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd1879903c5477eb329fb340bfe45f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":280},
                "size":{
                  "width":330,
                  "height":393}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录/u111.png"}},
{
          "id":"fa04e69bd15b49adb1674823c95b1c0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":333},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4285609dd883491a832d0418ab67c1b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":333},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a01b7054c8944b0f81ecdc1934dbfa60",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":329},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2c8f176d635471c965b97a83228ad80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":368},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a5cda7a5f94eb3bb8828404ce7ce46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":368},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bab6dbddf8f43039eaf43f7bf55d066",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":364},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"14a23de99c7b40a7b52811a64b367747",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":407},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16b475c2741f4a12be35e98c6865d157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":407},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b1e28875a344379bc946360c849fa06",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":403},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b8adc9bf760041b2b92dfb3627f74676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":481},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f055440fb8fe495881aba0b531af363f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":481},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22e795abe5c14cee91a9c4c7fd1386c9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":477},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f787b97cf7db45b3a1babf43f35ca8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":511},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ddfb7cc87d24603a41cce9c05cdbb57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":511},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e25d137f40d34a2bb596b2c129bd3d2b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":507},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2b15937fba149e5a9621721c48f8d2b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":618},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"035aa1231bff4e80900cf3fe6738a79f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":618},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3f2df95e3edd45f7999bb9c676c5b86d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":443},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb0e50d235b41ee8816d01358985af9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":443},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4ead11723ab4d138b4e6e170739e93c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":443},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3a485c793bb040f1adfa04191f48b5d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":546},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bedbaafd363a414fbc13c712e864546e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":546},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c4b6288ee6248bd9b565e5b1bf2e0a8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":991,
              "y":542},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f89fc13bda6d4b9d9c886770c20095a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":297},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f2a0550d194c419656d4d0ed28a498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":297},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca67cc600dae4920a492c0bbe2869645",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":297},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"971af848645242759808c219a2dba946",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1300,
              "y":112.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4587199f965146a3adbdf33ad17a0680",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":112},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "560780f4bbe643699c258ded15ca90c7":{
      "scriptId":"u0"},
    "306efb05eab448f6852a40b22f494e29":{
      "scriptId":"u1"},
    "8cb2ae04d5f2454e920e1075d84b4629":{
      "scriptId":"u2"},
    "f2cda5bcaa03423591470060c313403a":{
      "scriptId":"u3"},
    "feae179bf47c49b5b67d3a928b82aeff":{
      "scriptId":"u4"},
    "1b01ad5fced94cfe9072a2a65b34efc4":{
      "scriptId":"u5"},
    "1c23901a911e4f2fae4d42a98426612b":{
      "scriptId":"u6"},
    "115be9fdc8e148b784156637432c3c06":{
      "scriptId":"u7"},
    "72d28f1da9e84fc7bd5de5f531da3098":{
      "scriptId":"u8"},
    "c525dba787694edebfd2a8aca4ad40a5":{
      "scriptId":"u9"},
    "ea3a98fea02b4d9f88eb3b406ea550c6":{
      "scriptId":"u10"},
    "720d83d2e71e4fe6a0b634fdb51e98ff":{
      "scriptId":"u11"},
    "2eb2541edeac4c7782ace6cca321648d":{
      "scriptId":"u12"},
    "e010bb22b72f4464842c4ba7946e6a6a":{
      "scriptId":"u13"},
    "25a6b8c1846f4b01b0f4d1e270343dba":{
      "scriptId":"u14"},
    "089eb429cf6d4e9d95e7e2585563f6e1":{
      "scriptId":"u15"},
    "a111a70565214a748c24ca3863223995":{
      "scriptId":"u16"},
    "5314c218117d40aa9e9a0efc62ccd73f":{
      "scriptId":"u17"},
    "05a010b387674d758026ff35bde76f4a":{
      "scriptId":"u18"},
    "6411507f899a48d78737d77d22719393":{
      "scriptId":"u19"},
    "7776f07dcc1b44498637fb09742d4dec":{
      "scriptId":"u20"},
    "4a4e325c0f9f49adbb8698bf6a94bc12":{
      "scriptId":"u21"},
    "e47d1cc657f74f1d8def6b7257951a1f":{
      "scriptId":"u22"},
    "f60d732cc7ae4eb1a22740d9f8cae969":{
      "scriptId":"u23"},
    "f3da2aeda11644ecb8ecb39e7ba2fe95":{
      "scriptId":"u24"},
    "c1fce4b7c9b54745ba755a24033e5f08":{
      "scriptId":"u25"},
    "ef0de0518ed248b5b52f110f8ffada10":{
      "scriptId":"u26"},
    "364551fb013242deab069e6067c67cc3":{
      "scriptId":"u27"},
    "b494225763b14af5a8d434beb095c6dd":{
      "scriptId":"u28"},
    "c4a7a96dfa104f30aecfbc6ead862504":{
      "scriptId":"u29"},
    "f92c51627db0451ba36334f71545e4ea":{
      "scriptId":"u30"},
    "9e950f3590ad4e008688f423ed8baea2":{
      "scriptId":"u31"},
    "2621ff749ef0432ea9f10950abaea115":{
      "scriptId":"u32"},
    "175e33710f0c47e3ba6a8d5e6e7cd2db":{
      "scriptId":"u33"},
    "d9e4ed1c89ec4331b605a4e79e81dd2d":{
      "scriptId":"u34"},
    "35154b72d65044b29f65cc6b5dce4413":{
      "scriptId":"u35"},
    "d2e38558dba54e4a91a44af0557a4c2c":{
      "scriptId":"u36"},
    "7db057a2e581439d89171eb6be9c8053":{
      "scriptId":"u37"},
    "e2b4fb7b5d9247c7a0136a07fe3e4e62":{
      "scriptId":"u38"},
    "1ce8b679787842c799b52407adef7e29":{
      "scriptId":"u39"},
    "166e288cc0e04bee81866ceab489c08e":{
      "scriptId":"u40"},
    "14fba26200034bc8ac1dc3ed3a5d2cd3":{
      "scriptId":"u41"},
    "b97bd721a57140ff9e4be7b7ba31336f":{
      "scriptId":"u42"},
    "02ea46b71de048348316aa84210d0926":{
      "scriptId":"u43"},
    "051ef89d53334afcb191e5d183973bce":{
      "scriptId":"u44"},
    "115d4c8b82ca445aa4ade5262ec98c51":{
      "scriptId":"u45"},
    "3106734740df434bbf19428870c70a9a":{
      "scriptId":"u46"},
    "9cafb3989a0e4a208cc213bc97027075":{
      "scriptId":"u47"},
    "8b3efd7ff5d1471492ad8be7acea8f86":{
      "scriptId":"u48"},
    "1591c4cf178643ca84f2aad7d88cb6c1":{
      "scriptId":"u49"},
    "6e309d7fd082446b869333e474ad9363":{
      "scriptId":"u50"},
    "07600ee5e9724b488d99b44aab443898":{
      "scriptId":"u51"},
    "6040f6a1a8724b8db0bb925601bf4371":{
      "scriptId":"u52"},
    "d37c3f2ec11844e3a0542b473eebcd85":{
      "scriptId":"u53"},
    "ac2e0122652e40a08c66c99cf385bcff":{
      "scriptId":"u54"},
    "b65d9a2f21b443d7b3cc086c7c8700f8":{
      "scriptId":"u55"},
    "74c712c9739a42b4af17fbf7670c3114":{
      "scriptId":"u56"},
    "16314046a59848d2aefc262be5133323":{
      "scriptId":"u57"},
    "15334f0d27ca49e79d3dcc5a3f9463c1":{
      "scriptId":"u58"},
    "9c8734452b49447794e8ad9bc8edd54d":{
      "scriptId":"u59"},
    "eead397b0db44a99be5091deff456d7a":{
      "scriptId":"u60"},
    "419da717eb284bc5a8284e3790b427e0":{
      "scriptId":"u61"},
    "a6ffd5499a944853b1d306b3505c5e1f":{
      "scriptId":"u62"},
    "779faf8c0fce4f9285f2dec1dc9183bf":{
      "scriptId":"u63"},
    "b0a8f02021f2436da9fa15a9ab88491f":{
      "scriptId":"u64"},
    "8092171ea70e43798826375c2c4fba82":{
      "scriptId":"u65"},
    "8417a7bacd4646e79be6cf99c3cd247c":{
      "scriptId":"u66"},
    "9789031b688740e0b75964defd60128b":{
      "scriptId":"u67"},
    "cd2bf21afb694ad1b354b9e066e42318":{
      "scriptId":"u68"},
    "e19ef3b22cdc401c85fdf31ba63a90d3":{
      "scriptId":"u69"},
    "7ee5e378be544271a7b02e6b80924453":{
      "scriptId":"u70"},
    "fad83039f2f1465ab9a1f55da56b08d6":{
      "scriptId":"u71"},
    "0395f88002f249da965cfbb1cb78ff76":{
      "scriptId":"u72"},
    "343b2c128f414c059b263d4bf02fcba6":{
      "scriptId":"u73"},
    "4f359c193e9f47b581bc7f6b24a9bd55":{
      "scriptId":"u74"},
    "407137bf6e024e7f97ddd63a2e4ce20b":{
      "scriptId":"u75"},
    "eb6a93f60c994b249a2cab8db7896e43":{
      "scriptId":"u76"},
    "96f9a1c2981c4cd8961932482e800a46":{
      "scriptId":"u77"},
    "82a35f4ade9f4c7e8e0bcfc4f2e08ea0":{
      "scriptId":"u78"},
    "27014dad604142a3808eaaac8cf7b5a8":{
      "scriptId":"u79"},
    "1c47cb0d54204c5aa1499e290cfd9233":{
      "scriptId":"u80"},
    "e6d9541e949249fe892b5e935dd26da1":{
      "scriptId":"u81"},
    "a741888db4084806882c5709a1164f02":{
      "scriptId":"u82"},
    "4cde0d11d7924c9ea1ce72af54a1ebc6":{
      "scriptId":"u83"},
    "4d681f4eff36409d916d35220a0a6850":{
      "scriptId":"u84"},
    "80d7c79ecef44090a51c592553dddd1f":{
      "scriptId":"u85"},
    "3c2710bf7ea64ef3aaa9eab174e611fb":{
      "scriptId":"u86"},
    "13e349bcbea849f6b35c5e79d7bdf6c6":{
      "scriptId":"u87"},
    "b97fddffedec4112a5ef1e7e631380f8":{
      "scriptId":"u88"},
    "4b268b593a374f38bedd8c89eb4ae414":{
      "scriptId":"u89"},
    "40111fbf302242b1ba16374ed6f2cf1b":{
      "scriptId":"u90"},
    "2f9f4f51cddb4eb5973c5013c55c59d3":{
      "scriptId":"u91"},
    "2b2c59550ab04509b30d19612ec2cd71":{
      "scriptId":"u92"},
    "2f8e844203394dcca37acebd2f71b226":{
      "scriptId":"u93"},
    "7281075920de43979446ca9280925791":{
      "scriptId":"u94"},
    "f6b8fff8bc64477986f8a6e8bea5409a":{
      "scriptId":"u95"},
    "bc6e729ea2154b71a36e9a7b40c37832":{
      "scriptId":"u96"},
    "146f1f9ec5ad442c930a5173e3213128":{
      "scriptId":"u97"},
    "054299ef9b994955be800d7d0689ef0d":{
      "scriptId":"u98"},
    "ad83a331e4144019b166816865bda767":{
      "scriptId":"u99"},
    "7b6106c39bf34b09a1b324ab34a98864":{
      "scriptId":"u100"},
    "7ba8c24992664320b278e6b30e9d0faa":{
      "scriptId":"u101"},
    "2468cc109a94456db7e06ab144ff5ba3":{
      "scriptId":"u102"},
    "0e1f7784255c45dcba719c56ba68039d":{
      "scriptId":"u103"},
    "f6eb36345d8445b090a390001067aae3":{
      "scriptId":"u104"},
    "52336e439d244d6196fc95b0ff3d4d3d":{
      "scriptId":"u105"},
    "e57ce29f042e48869357ce373ecad700":{
      "scriptId":"u106"},
    "7972db29342e4abe95a94f1029a6d780":{
      "scriptId":"u107"},
    "ebfdd089648147adb4ec9cb2d27ce478":{
      "scriptId":"u108"},
    "b4399fb9e74146179e5e0602b2d1ec23":{
      "scriptId":"u109"},
    "03015ef37cee423ba089924f9a6bf8ae":{
      "scriptId":"u110"},
    "6bb8487420404448a389409308277a8f":{
      "scriptId":"u111"},
    "ffd1879903c5477eb329fb340bfe45f6":{
      "scriptId":"u112"},
    "fa04e69bd15b49adb1674823c95b1c0c":{
      "scriptId":"u113"},
    "4285609dd883491a832d0418ab67c1b0":{
      "scriptId":"u114"},
    "a01b7054c8944b0f81ecdc1934dbfa60":{
      "scriptId":"u115"},
    "f2c8f176d635471c965b97a83228ad80":{
      "scriptId":"u116"},
    "b5a5cda7a5f94eb3bb8828404ce7ce46":{
      "scriptId":"u117"},
    "7bab6dbddf8f43039eaf43f7bf55d066":{
      "scriptId":"u118"},
    "14a23de99c7b40a7b52811a64b367747":{
      "scriptId":"u119"},
    "16b475c2741f4a12be35e98c6865d157":{
      "scriptId":"u120"},
    "9b1e28875a344379bc946360c849fa06":{
      "scriptId":"u121"},
    "b8adc9bf760041b2b92dfb3627f74676":{
      "scriptId":"u122"},
    "f055440fb8fe495881aba0b531af363f":{
      "scriptId":"u123"},
    "22e795abe5c14cee91a9c4c7fd1386c9":{
      "scriptId":"u124"},
    "f787b97cf7db45b3a1babf43f35ca8aa":{
      "scriptId":"u125"},
    "1ddfb7cc87d24603a41cce9c05cdbb57":{
      "scriptId":"u126"},
    "e25d137f40d34a2bb596b2c129bd3d2b":{
      "scriptId":"u127"},
    "b2b15937fba149e5a9621721c48f8d2b":{
      "scriptId":"u128"},
    "035aa1231bff4e80900cf3fe6738a79f":{
      "scriptId":"u129"},
    "3f2df95e3edd45f7999bb9c676c5b86d":{
      "scriptId":"u130"},
    "9fb0e50d235b41ee8816d01358985af9":{
      "scriptId":"u131"},
    "d4ead11723ab4d138b4e6e170739e93c":{
      "scriptId":"u132"},
    "3a485c793bb040f1adfa04191f48b5d7":{
      "scriptId":"u133"},
    "bedbaafd363a414fbc13c712e864546e":{
      "scriptId":"u134"},
    "0c4b6288ee6248bd9b565e5b1bf2e0a8":{
      "scriptId":"u135"},
    "f89fc13bda6d4b9d9c886770c20095a7":{
      "scriptId":"u136"},
    "d8f2a0550d194c419656d4d0ed28a498":{
      "scriptId":"u137"},
    "ca67cc600dae4920a492c0bbe2869645":{
      "scriptId":"u138"},
    "971af848645242759808c219a2dba946":{
      "scriptId":"u139"},
    "4587199f965146a3adbdf33ad17a0680":{
      "scriptId":"u140"}}});