$axure.loadCurrentPage({
  "url":"待确认内容.html",
  "generationDate":new Date(1660199389817.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"38f1170e11c34366b57b54d6f1a039de",
    "type":"Axure:Page",
    "name":"待确认内容",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"97f6343e2ea44308932017591b7e76d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":64},
            "size":{
              "width":431,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea57dff120e493fae13d0df367dc6d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":64},
                "size":{
                  "width":431,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "97f6343e2ea44308932017591b7e76d4":{
      "scriptId":"u0"},
    "fea57dff120e493fae13d0df367dc6d4":{
      "scriptId":"u1"}}});