$axure.loadCurrentPage({
  "url":"业务统计.html",
  "generationDate":new Date(1660199389794.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cf35368098fc4d08b6bbddf770c1b0dc",
    "type":"Axure:Page",
    "name":"业务统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"82f74c92f228413c9c8dff40ee17f09c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":1100,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42ff664be5c46898f1c31905d663d64",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8fa4de25a9ca43e9bcb3bc0b7e1c2bfe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"de729040d4544068898f7ee9e8e0528a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2e704061f6443ff9491b7ab4bccd83f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"c87578b1ada045efb49ce49d78d4430f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30e3326483a74d029e8a0168f48b5040",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"d8963d5992864b81a70ac38e88d75220",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71464f39f73f4761a3a96688f0322ea8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"320af9a481a9439e8f4de585f2d136d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b6dadd63e194c11af66df5e781b968d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"a5b2dd969e1249c8b70a5b18362a1544",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e54fb120fe304dbfa4785ff905768c6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"f7104633aee54f6fbf0535ee0cca0136",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"744ddf5dc2b9487db55a20aea0939884",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"4a948f4da9304a2a9cf6f2700158701c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54f532d500ed492f943944340264c521",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"35cdb9cf0c8343f3a26d949c7a6e25ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69d8b1b33fdd47459ad5b5f533f5e6be",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"52f2b1df2d1d493abe312da821b4c507",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c708919d3eb407cb234b0a9385793d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"56b5b206111444808ff2db619ac1f249",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4a608570ba7433c82144060f74268c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"aa6d9180314942a19839217bcbff9600",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f59147335ed74bef8077035c669cdf8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"c6ea035938c54ee589289ad64cf8c0f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ebe914a6e6444c2b6b4b7ae3686783e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"2db88ada5f954cd6935291fb545db53b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de21c4820dd04d25be0408593fa91ac3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"b298af00364c4879a4f2d21617b5d2ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c962c85dfdb4e2da15f3d0af2bbb9f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"fa736b3e405943b6ba0e91fcb3d9e058",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"742753fbd1794f7d9fa2b5bd24e0b1cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"30bb7523944c4906a736adedfe9cdccf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"154e20b5d4184f4eb03ec4567ed66dc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"ba9ca4d4119f4c1ab2127d5b4183e931",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b89037f7b964e5a82dfa97130092acd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"a4f3a5db922348aab346b5f47995db8f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3f3a536b932492dac7dbc92e18ba5dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"64b1d33843db4140b1c75ba4b53ea061",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24e8f22ba5e244d4a01d54cdd3c3679a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"1597dd7f919e4cf59b48cc73343f3ce7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac5cc917b0a8449296bb16d790df2575",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"7cceea4f89544689b3ec07c94f9398dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4354b25a684f445f877640c9474438fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"f1d1063bc1db4a18a9f356994062f640",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fef26d4746f409d81905eb9e2c92bc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"ee8d04cd8abb4140b67d3a3dfd77b3e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"229df2c1587644b18a7ff76d34dd4219",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"13de3575b6a34f559a0ea0bb1597ab0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":900,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7417253d4d154a86b24583b4a9b1ae2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":900,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"48a3a45f6d1e4cf0b01644485a38d82b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":900,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb23c6e6c66a45eb8afa880ec6cb22be",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":900,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"2f8fb7b2183e416bb571fac45039c994",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":900,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e03d4bae2fd459e8137e75739dc016c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":900,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"cc7c2e7c237349ffb48faeaa9f81da5a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1dfa2382a3ae487e88a6b3c98e9aa5e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u12.png"}},
{
              "id":"e779680af6e44db69851b8aad96fc431",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e390d84bb014c1dad45ef34a3a8dea3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u4.png"}},
{
              "id":"85bee64234ef44059f1bdaf5ea5d38ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91e6524bbb0243ae80f7abcfad12ae67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u44.png"}},
{
              "id":"1b2fe10447d14613819ca7421008e203",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1000,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a614a99cff3d43ddb1a5ffce3a224f30",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1000,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u18.png"}},
{
              "id":"57b23582dd3f40839db68b67b99f8d00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1000,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1377a8ee39354844aaaf128773de349e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1000,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u10.png"}},
{
              "id":"a39ed23a372b4c4881f6d34c28eff0ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1000,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d491717e5c134c6cbd464e310baea952",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1000,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/流程配置/u50.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "82f74c92f228413c9c8dff40ee17f09c":{
      "scriptId":"u0"},
    "d42ff664be5c46898f1c31905d663d64":{
      "scriptId":"u1"},
    "8fa4de25a9ca43e9bcb3bc0b7e1c2bfe":{
      "scriptId":"u2"},
    "cc7c2e7c237349ffb48faeaa9f81da5a":{
      "scriptId":"u3"},
    "1dfa2382a3ae487e88a6b3c98e9aa5e5":{
      "scriptId":"u4"},
    "7cceea4f89544689b3ec07c94f9398dc":{
      "scriptId":"u5"},
    "4354b25a684f445f877640c9474438fa":{
      "scriptId":"u6"},
    "d8963d5992864b81a70ac38e88d75220":{
      "scriptId":"u7"},
    "71464f39f73f4761a3a96688f0322ea8":{
      "scriptId":"u8"},
    "f7104633aee54f6fbf0535ee0cca0136":{
      "scriptId":"u9"},
    "744ddf5dc2b9487db55a20aea0939884":{
      "scriptId":"u10"},
    "52f2b1df2d1d493abe312da821b4c507":{
      "scriptId":"u11"},
    "0c708919d3eb407cb234b0a9385793d4":{
      "scriptId":"u12"},
    "fa736b3e405943b6ba0e91fcb3d9e058":{
      "scriptId":"u13"},
    "742753fbd1794f7d9fa2b5bd24e0b1cb":{
      "scriptId":"u14"},
    "c6ea035938c54ee589289ad64cf8c0f0":{
      "scriptId":"u15"},
    "0ebe914a6e6444c2b6b4b7ae3686783e":{
      "scriptId":"u16"},
    "a4f3a5db922348aab346b5f47995db8f":{
      "scriptId":"u17"},
    "e3f3a536b932492dac7dbc92e18ba5dc":{
      "scriptId":"u18"},
    "13de3575b6a34f559a0ea0bb1597ab0e":{
      "scriptId":"u19"},
    "7417253d4d154a86b24583b4a9b1ae2c":{
      "scriptId":"u20"},
    "1b2fe10447d14613819ca7421008e203":{
      "scriptId":"u21"},
    "a614a99cff3d43ddb1a5ffce3a224f30":{
      "scriptId":"u22"},
    "de729040d4544068898f7ee9e8e0528a":{
      "scriptId":"u23"},
    "d2e704061f6443ff9491b7ab4bccd83f":{
      "scriptId":"u24"},
    "e779680af6e44db69851b8aad96fc431":{
      "scriptId":"u25"},
    "7e390d84bb014c1dad45ef34a3a8dea3":{
      "scriptId":"u26"},
    "f1d1063bc1db4a18a9f356994062f640":{
      "scriptId":"u27"},
    "5fef26d4746f409d81905eb9e2c92bc3":{
      "scriptId":"u28"},
    "320af9a481a9439e8f4de585f2d136d4":{
      "scriptId":"u29"},
    "2b6dadd63e194c11af66df5e781b968d":{
      "scriptId":"u30"},
    "4a948f4da9304a2a9cf6f2700158701c":{
      "scriptId":"u31"},
    "54f532d500ed492f943944340264c521":{
      "scriptId":"u32"},
    "56b5b206111444808ff2db619ac1f249":{
      "scriptId":"u33"},
    "a4a608570ba7433c82144060f74268c0":{
      "scriptId":"u34"},
    "30bb7523944c4906a736adedfe9cdccf":{
      "scriptId":"u35"},
    "154e20b5d4184f4eb03ec4567ed66dc0":{
      "scriptId":"u36"},
    "2db88ada5f954cd6935291fb545db53b":{
      "scriptId":"u37"},
    "de21c4820dd04d25be0408593fa91ac3":{
      "scriptId":"u38"},
    "64b1d33843db4140b1c75ba4b53ea061":{
      "scriptId":"u39"},
    "24e8f22ba5e244d4a01d54cdd3c3679a":{
      "scriptId":"u40"},
    "48a3a45f6d1e4cf0b01644485a38d82b":{
      "scriptId":"u41"},
    "bb23c6e6c66a45eb8afa880ec6cb22be":{
      "scriptId":"u42"},
    "57b23582dd3f40839db68b67b99f8d00":{
      "scriptId":"u43"},
    "1377a8ee39354844aaaf128773de349e":{
      "scriptId":"u44"},
    "c87578b1ada045efb49ce49d78d4430f":{
      "scriptId":"u45"},
    "30e3326483a74d029e8a0168f48b5040":{
      "scriptId":"u46"},
    "85bee64234ef44059f1bdaf5ea5d38ce":{
      "scriptId":"u47"},
    "91e6524bbb0243ae80f7abcfad12ae67":{
      "scriptId":"u48"},
    "ee8d04cd8abb4140b67d3a3dfd77b3e4":{
      "scriptId":"u49"},
    "229df2c1587644b18a7ff76d34dd4219":{
      "scriptId":"u50"},
    "a5b2dd969e1249c8b70a5b18362a1544":{
      "scriptId":"u51"},
    "e54fb120fe304dbfa4785ff905768c6a":{
      "scriptId":"u52"},
    "35cdb9cf0c8343f3a26d949c7a6e25ee":{
      "scriptId":"u53"},
    "69d8b1b33fdd47459ad5b5f533f5e6be":{
      "scriptId":"u54"},
    "aa6d9180314942a19839217bcbff9600":{
      "scriptId":"u55"},
    "f59147335ed74bef8077035c669cdf8c":{
      "scriptId":"u56"},
    "ba9ca4d4119f4c1ab2127d5b4183e931":{
      "scriptId":"u57"},
    "9b89037f7b964e5a82dfa97130092acd":{
      "scriptId":"u58"},
    "b298af00364c4879a4f2d21617b5d2ea":{
      "scriptId":"u59"},
    "8c962c85dfdb4e2da15f3d0af2bbb9f4":{
      "scriptId":"u60"},
    "1597dd7f919e4cf59b48cc73343f3ce7":{
      "scriptId":"u61"},
    "ac5cc917b0a8449296bb16d790df2575":{
      "scriptId":"u62"},
    "2f8fb7b2183e416bb571fac45039c994":{
      "scriptId":"u63"},
    "7e03d4bae2fd459e8137e75739dc016c":{
      "scriptId":"u64"},
    "a39ed23a372b4c4881f6d34c28eff0ec":{
      "scriptId":"u65"},
    "d491717e5c134c6cbd464e310baea952":{
      "scriptId":"u66"}}});