$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1660115816734.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bc9c0331f294453884fccdc55ab8e06f",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8cb2ae04d5f2454e920e1075d84b4629",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":298,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2cda5bcaa03423591470060c313403a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":298,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8cb2ae04d5f2454e920e1075d84b4629":{
      "scriptId":"u0"},
    "f2cda5bcaa03423591470060c313403a":{
      "scriptId":"u1"}}});