$axure.loadCurrentPage({
  "url":"定义.html",
  "generationDate":new Date(1660199389387.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f65d719a78254865bee0bd5c0863cd20",
    "type":"Axure:Page",
    "name":"定义",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8496735cdc4417fb0b585d816d868a3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":40},
            "size":{
              "width":560,
              "height":187}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b7c90942aa34513ae2043930f112c28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e410b2173794f1087d67c6986fdf9ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u1.png"}},
{
              "id":"76c23ff4830249e3a18fb940863c7a77",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78f5ae0920814956b70633e0af546391",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u1.png"}},
{
              "id":"e95a80c531ec499c9a80cf0393647df4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38dfe595a6b54de1a6f94261022dfb7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u1.png"}},
{
              "id":"1a48b655674d49afacbfdb0eeb2ea828",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":410,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"002bf5faf2c2472988d78f03c315217c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":410,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u3.png"}},
{
              "id":"3ab3b832abf74964947acdfcd676eb6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":410,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1727848d9c0a4390a36667d255920e13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":410,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u3.png"}},
{
              "id":"f3d227fe8ae649cda8012fe7b1d30d6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":60},
                "size":{
                  "width":410,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1847c2b0f0b74f4e954faa2afdf11cd9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":60},
                    "size":{
                      "width":410,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u3.png"}},
{
              "id":"2dc2acef83e14b2b9740ee97c122da20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":157},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9438e843d9af4cccb58a6113a992fd21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":157},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u21.png"}},
{
              "id":"11f226354dfd4073b40bd278c943e4df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":157},
                "size":{
                  "width":410,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2fac12dca18846c8a5aed060c6bd4332",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":157},
                    "size":{
                      "width":410,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u23.png"}},
{
              "id":"d15b9e6edebc420ab24aff3456fcd773",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da7945415f6f41aeb7b12cb95c2ade29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u1.png"}},
{
              "id":"89985d6fecae4c208110a1130107a385",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":90},
                "size":{
                  "width":410,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b849e2e21154f2fb6376e35ee9b9df0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":90},
                    "size":{
                      "width":410,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u3.png"}},
{
              "id":"996a4a4d57bd47839a50736c16a2cf84",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc0ca41d6b864944998bcfdfea01637d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":150,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u17.png"}},
{
              "id":"1ec6b8dd7f1247f7a44c3d18ae6f4394",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":120},
                "size":{
                  "width":410,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1db36f6dc1f547de962094c5fe7d4c32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":120},
                    "size":{
                      "width":410,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定义/u19.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "a8496735cdc4417fb0b585d816d868a3":{
      "scriptId":"u0"},
    "5b7c90942aa34513ae2043930f112c28":{
      "scriptId":"u1"},
    "4e410b2173794f1087d67c6986fdf9ad":{
      "scriptId":"u2"},
    "1a48b655674d49afacbfdb0eeb2ea828":{
      "scriptId":"u3"},
    "002bf5faf2c2472988d78f03c315217c":{
      "scriptId":"u4"},
    "76c23ff4830249e3a18fb940863c7a77":{
      "scriptId":"u5"},
    "78f5ae0920814956b70633e0af546391":{
      "scriptId":"u6"},
    "3ab3b832abf74964947acdfcd676eb6f":{
      "scriptId":"u7"},
    "1727848d9c0a4390a36667d255920e13":{
      "scriptId":"u8"},
    "e95a80c531ec499c9a80cf0393647df4":{
      "scriptId":"u9"},
    "38dfe595a6b54de1a6f94261022dfb7b":{
      "scriptId":"u10"},
    "f3d227fe8ae649cda8012fe7b1d30d6b":{
      "scriptId":"u11"},
    "1847c2b0f0b74f4e954faa2afdf11cd9":{
      "scriptId":"u12"},
    "d15b9e6edebc420ab24aff3456fcd773":{
      "scriptId":"u13"},
    "da7945415f6f41aeb7b12cb95c2ade29":{
      "scriptId":"u14"},
    "89985d6fecae4c208110a1130107a385":{
      "scriptId":"u15"},
    "0b849e2e21154f2fb6376e35ee9b9df0":{
      "scriptId":"u16"},
    "996a4a4d57bd47839a50736c16a2cf84":{
      "scriptId":"u17"},
    "cc0ca41d6b864944998bcfdfea01637d":{
      "scriptId":"u18"},
    "1ec6b8dd7f1247f7a44c3d18ae6f4394":{
      "scriptId":"u19"},
    "1db36f6dc1f547de962094c5fe7d4c32":{
      "scriptId":"u20"},
    "2dc2acef83e14b2b9740ee97c122da20":{
      "scriptId":"u21"},
    "9438e843d9af4cccb58a6113a992fd21":{
      "scriptId":"u22"},
    "11f226354dfd4073b40bd278c943e4df":{
      "scriptId":"u23"},
    "2fac12dca18846c8a5aed060c6bd4332":{
      "scriptId":"u24"}}});